### PR TITLE
Fix LineEvent timestamp doc

### PR DESCRIPTION
**Pull request by mpi3d**
Fix documentation on `LineEvent::timestamp()`.

According to the Linux documentation, the timestamp is `CLOCK_MONOTONIC` by default: [gpio.h#L286](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/gpio.h#n286).

Please see [#68 comment](https://github.com/rust-embedded/gpio-cdev/issues/68#issuecomment-1174454730).

### CODE REVIEW

**Comment by posborne** [comment]
The default clock used depends on the kernel version.  https://github.com/torvalds/linux/commit/26d060e47e25f2c715a1b2c48fea391f67907a30 notes that this change to the default was made with kernel 5.7, so a note to that effect may be nice.

**Comment by mpi3d** [comment]
> The default clock used depends on the kernel version. [torvalds/linux@26d060e](https://github.com/torvalds/linux/commit/26d060e47e25f2c715a1b2c48fea391f67907a30) notes that this change to the default was made with kernel 5.7, so a note to that effect may be nice.

Ok, thanks, I added a new commit for that.

**Review by eldruin — APPROVED** [review]
Great, thank you!
bors r+

**Comment by eldruin** [comment]
Sorry, could you also raise the MSRV to 1.56 and note that change in the changelog?

**Comment by mpi3d** [comment]
Anyway: done

**Review by eldruin — APPROVED** [review]
Thank you!
bors r+

**Comment by mpi3d** [comment]
Guessing it needs `1.59`

**Comment by eldruin** [comment]
It seems we have some more problems :/

**Comment by mpi3d** [comment]
@eldruin I force pushed a commit to fix it. Can you trigger a new build please?

**Comment by eldruin** [comment]
I fixed our CI in #71. Could you rebase this?

**Comment by mpi3d** [comment]
Done

**Review by eldruin — APPROVED** [review]
Thank you for everything!
bors r+

**Pull request merged**
