### PR TITLE
Fix ci

### LINKED ISSUE #73: Fix CI
CI is currently broken, also we need to migrate to GitHub MQ.

### PR DESCRIPTION
**Pull request by Dirreke**
Close #73 
Close #72 

Update the ci target to allign with rust-lang. 

because of https://github.com/rust-lang/compiler-team/issues/648 , MIPS* target has been degreed to Tier3.
remove mips-unknown-linux-gnu
remove mips64-unknown-linux-gnuabi64
remove mips64el-unknown-linux-gnuabi64
remove mipsel-unknown-linux-gnu

add aarch64-unknown-linux-musl
add arm-unknown-linux-gnueabihf
add riscv64gc-unknown-linux-gnu

### CODE REVIEW

**Comment by Dirreke** [comment]
Could I update MSRV to 1.65.0? (Because nix has updated it to 1.65.0)

**Comment by ryankurte** [comment]
> Could I update MSRV to 1.65.0? (Because nix has updated it to 1.65.0)

looks like we're still pulling in `nix@0.23` here and in `linux-embedded-hal`? in principle we can update this to `0.27` and increase the MSRV to match, with the caveat we will also need to bump this upstream and in the other linux packages.

rust [`1.65.0`](https://releases.rs/docs/1.65.0/) is ~10 months old so that seems okay to me, any other takes @rust-embedded/embedded-hal folks?

**Comment by Dirreke** [comment]
I originally planned to update dependencies in # 72. However it seems that the old nix is not supported for these new target. Therefore, I will merge #72 with this PR

**Comment by Dirreke** [comment]
fixed

**Comment by eldruin** [comment]
I think 1.65.0 is probably fine for `linux-embedded-hal`.
Could you look at the failures in CI?

**Comment by Dirreke** [comment]
I  mistakenly introduce some code only available in version 1.66.0 and above.

I fixed it, let's give it another try, Thanks

**Review by eldruin — COMMENTED** [review]
Thanks!
Could you add an entry to the changelog about the MSRV change and remove the bors.toml file?

**Comment by Dirreke** [comment]
Done!

**Comment by Dirreke** [comment]
Could you review it? @eldruin

**Review by eldruin — APPROVED** [review]
Looks good to me, thanks!

**Comment by Dirreke** [comment]
any idea? @eldruin

**Comment by eldruin** [comment]
No idea, all the checks pass. Somehow the merge queue seems not to receive the results.

**Review by eldruin — COMMENTED** [review]
Ah, I have it now.
Could you replace the `on:...` at the beginning of the `ci.yml` with this?:
```yaml
on:
  push: # Run CI for all branches except GitHub merge queue tmp branches
    branches-ignore:
    - "gh-readonly-queue/**"
  pull_request: # Run CI for PRs on any branch
  merge_group: # Run CI for the GitHub merge queue
```

**Comment by Dirreke** [comment]
Done! @eldruin

**Review by eldruin — APPROVED** [review]
Alright, hopefully it works now. Thanks!

**Pull request merged**
