### PR TITLE
Replace error-chain with failure

### PR DESCRIPTION
**Pull request by chris-ricketts**
error-chain is going to be deprecated.

Using failure means it is easier to integrate with frameworks such as actix as well as requiring less boilerplate in end user binaries.

### CODE REVIEW

**Comment by posborne** [comment]
Hi @chris-ricketts, thanks for the PR.  Agree that error-chain needs to go away; it was the flavor of the day at the time but, in hindsight, wasn't an appropriate choice for this crate.

Right now I'm debating whether it makes sense to have the failure dependency or whether it might be better to just expose a custom error enumeration.  Now that (as of 1.30.0) `std::Error` has `source` we could still daylight the underlying nix (or whatever) error as needed.

For brevity in tests/examples I think `failure` as a dev-dependency (if it simplifies anything) is reasonable.

Thoughts?

**Comment by fpagliughi** [comment]
Hey @posborne, do you know of any crates that show the use of `source` with `std::Error` that would serve as a good example?

**Comment by posborne** [comment]
This thread has some good information and this post contains links to how @burntsushi is doing things in several places.  There is certainly some extra boilerplate in doing things this way but I think it is worthwhile to be explicit about errors in a crate like this one.

https://users.rust-lang.org/t/error-chain-is-no-longer-maintained/27561/8

Admittedly I still need to do some reading and I don't think some of these solutions solve the backtrace problem.  With a proper breakdown of errors, however, I think this is probably not too big of a problem in practice (for this crate).

**Comment by posborne** [comment]
Another example I saw while looking at a new crate from Alex: https://github.com/alexcrichton/wast/blob/master/src/lib.rs#L165-L214

**Comment by chris-ricketts** [comment]
Hi @posborne - thanks for the feedback, research and links to the examples.

I think an approach like Alex's would be the best plan.
It gets rid of a dependency and gives the end user the choice.

[`failure::Fail`](https://docs.rs/failure/0.1.6/failure/trait.Fail.html) has a blanket implementation for anything that implements `std::error::Error + Display` and is also `'Send + Sync + 'static` so I think we should try to fulfill those requirements. 

I will close this PR and open an issue that references it. 
I'm happy to try and complete the task.

**Comment by posborne** [comment]
Thanks @chris-ricketts, absolutely take a shot, otherwise I can certainly take on the task as well.  Just let me know.

**Pull request closed without merging**
