### PR TITLE
prepare for 0.6.0

### LINKED ISSUE #75: New release?
It has been 2 years since it released last time. Could we make a new release?

### PR DESCRIPTION
**Pull request by Dirreke**
Close #75

### CODE REVIEW

**Review by eldruin — COMMENTED** [review]
Thanks!
Could you also add a link for the version at the bottom of the changelog?
Also, could you bump make the release 0.6.0 instead?
I think `nix` is part of the public interface and that change was breaking.

**Comment by Dirreke** [comment]
Sure, thanks!

**Review by eldruin — APPROVED** [review]
Thank you!

**Comment by eldruin** [comment]
Version 0.6.0 is now published, thanks!

**Pull request merged**
