### PR TITLE
Add MSRV 1.34.0

### PR DESCRIPTION
**Pull request by eldruin**
See: https://github.com/rust-embedded/wg/issues/445

### CODE REVIEW

**Comment by otavio** [comment]
Due to use of `Kleene operator for "at most one" operator`, the MSRV needs to be raised to 1.32 it seems.

**Comment by otavio** [comment]
The error comes from `anyhow` from the `dev-dependencies`. So maybe it could be reworked?

**Comment by therealprof** [comment]
Raising the MSRV to 1.32 sounds fine to me.

**Comment by eldruin** [comment]
Rust 1.32.0 was not enough. As per anyhow 1.0.28 documentation, Rust 1.34+ is necessary. However, it is not explicitly stated there that 1.34.0 is the MSRV.
With 1.34.0 this crate builds fine.

**Pull request merged**
